# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kent Ou
tagline:          'My Personal Blog'
description:      'My Personal Blog For All The Things!'
url:              kent10ou.github.io
baseurl:          /

author:
  name:           'Kent Ou'
  twitter:        https://twitter.com/kent10ou
  linkedin:       https://linkedin/com/in/kent10ou

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kent10ou
