# Site settings
title: Kent Ou
header-img: img/home-bg.jpg
email: kent10ou@gmail.com
description: "Kent Ou's Blog: My Journey Through Telegraph Academy!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: kent10ou
github_username:  kent10ou
facebook_username: 
linkedin_username: kent10ou

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
