# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kent Ou
tagline:          'My Personal Blog'
description:      ''
url:              kent10ou.github.io
baseurl:          /
params:
  themeColor: "theme-base-09"

author:
  name:           'Kent Ou'
  url:            https://twitter.com/kent10ou

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/kent10ou
